// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Device struct {
	ID              int64
	FriendlyName    string
	HardwareVersion string
	Isenabled       bool
	IsmeshSupported bool
	Macid           string
	Manufacturer    string
	ManufacturerOui string
	Model           string
	Name            string
	Role            string
	Serial          string
	SoftwareVersion string
	Type            string
	UpdateState     string
}

type Signal struct {
	ID          int64
	Snapshotid  int64
	AntennaUsed string
	Generation  string
	Band        string
	Bars        float64
	Cid         int64
	Enbid       int64
	Gnbid       int64
	Rsrp        int64
	Rsrq        int64
	Rssi        int64
	Sinr        int64
}

type Snapshot struct {
	ID        int64
	Deviceid  int64
	CreatedAt time.Time
	Uptime    int64
}
